version: "3.8"

services:

  postgres:
    build: 
        context: ../Learn-Database/
        dockerfile: Dockerfile
    environment:
      POSTGRES_USER: node_user
      POSTGRES_PASSWORD: node_password
      POSTGRES_DB: learn_db

#   redis:
#     image: redis:3.2-alpine

  node:
    build: 
      context: ../LearnStudio-Back/learn-studio-api
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    #   - redis
    ports:
      - 3000
    environment:
        DATABASE_URL: 'postgres://node_user:node_password@postgres:5432/learn_db'
    #   REDIS_HOST: 'redis:6379'

  angular:
    build:
      context: ../LearnStudio-Front/learnstudio
      dockerfile: Dockerfile.prod
    depends_on:
      - node
#      - redis
    ports:
      - 80
    environment:
        BACKEND_INTERNAL_HOST: 'node:3000'
        # BACKEND_EXTERNAL_HOST: 'http://learn-studio-api.test'
        BACKEND_EXTERNAL_HOST: 'http://learn-studio-api.test:8181'
        #   REDIS_HOST: 'redis:6379'


  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - node
      - angular
    ports:
      - 8181:80
      - 4443:443